language: node_js
node_js:
  - 10.18.0
cache: npm

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skin-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
